#ifndef NOTE_H
#define NOTE_H

#include <QString>
#include <QDateTime>
#include <QtGlobal>

class Note {
public:
    Note(QString noteTypeId, QString noteTitle);

    //Getters
    QString getTitle() const { return title; }
    qint64 getId() const { return id; }
    QString getTypeId() const { return typeId; }

    //Setters
    void setId(qint64 newId);
    void setTitle(const QString& newTitle);
    void setContent(const QString& newContent);
    void setTypeId(const QString& newTypeId);

    //Methods
    void display() const;

private:
    // ID is generated by SQLite AUTOINCREMENT; -1 means not persisted yet.
    qint64 id = -1;
    QString typeId;
    QString title;
    QString content;
    QDateTime lastModified;

};

#endif