#ifndef NOTE_H
#define NOTE_H

#include <QString>
#include <QDateTime>
#include <QtGlobal>
#include "../api/INote.h"

class Note : public INote {
public:
    Note(QString noteTypeId, QString noteTitle);

	// Accessors
	virtual qint64 noteId() const override { return m_noteId; }
	virtual QString typeId()const override { return m_typeId; }
	virtual QString content() const override { return m_content; }
	virtual QString title() const override { return m_title; }
	virtual QDateTime createdAt() const override { return m_createdAt; }
	virtual QDateTime lastModified() const override { return m_lastModified; }

	// Mutators
	virtual void setNoteId(qint64 newId) override;
	virtual void setTypeId(const QString& newTypeId) override;
	virtual void setContent(const QString& newContent) override;
	virtual void setTitle(const QString& newTitle) override;
	virtual void setCreatedAt(const QDateTime& dt) override;
	virtual void setLastModified(const QDateTime& dt) override;
	
	// Methods
	virtual QString displayText() const override;
    void display() const;

	bool isSecured() const { return m_isSecured; }
	QString encryptionSalt() const { return m_encryptionSalt; }
	QString encryptionIv() const { return m_encryptionIv; }
	QString encryptionTag() const { return m_encryptionTag; }

	void setSecured(bool secured);
	void setEncryptionSalt(const QString &salt);
	void setEncryptionIv(const QString &iv);
	void setEncryptionTag(const QString &tag);

private:
    // ID is generated by SQLite AUTOINCREMENT; -1 means not persisted yet.
    qint64 m_noteId = -1;
    QString m_typeId;
    QString m_title;
    QString m_content;
    QDateTime m_createdAt;
    QDateTime m_lastModified;
	bool m_isSecured = false;
	QString m_encryptionSalt;
	QString m_encryptionIv;
	QString m_encryptionTag;

};

#endif